name: goramp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+2
publish_to: none
#2.11.0-186.0.dev
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.6
  firebase_core: ^1.10.4
  cloud_firestore: ^3.1.3
  firebase_auth: ^3.3.2
  firebase_auth_oauth: ^1.1.0
  firebase_storage: ^10.2.2
  cloud_functions: ^3.2.2
  firebase_messaging: ^11.2.2
  firebase_app_check: ^0.0.6+1
  twitter_login: ^4.0.1
  flutter_facebook_auth: ^3.5.6+3
  passbase_flutter: 2.7.6-nullsafety.0
  go_router: #^2.2.8
    #path: ../../../../libs/go_router
    git:
      url: https://github.com/peerwaya/go_router
  cryptography: ^2.0.1
  google_fonts: ^2.1.0
  animations: ^2.0.0
  cupertino_icons: ^1.0.2
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  qr_flutter: ^4.0.0
  flutter_sticky_header:
    git:
      url: https://github.com/UnderKoen/flutter_sticky_header
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.6
  timeago: ^3.1.0
  rxdart: ^0.27.2
  nanoid: ^1.0.0
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  path: ^1.8.0
  sign_in_with_apple: ^3.3.0
  # firebase_app_check: ^0.0.2+1
  # flutter_incall_manager:
  #   git:
  #     url: https://github.com/peerwaya/flutter-incall-manager.git
  image: ^3.0.1
  recase: ^4.0.0
  dotted_border: ^2.0.0+1
  material_design_icons_flutter: ^5.0.6295
  share_plus: ^2.1.2
  uni_links: ^0.5.1
  connectivity_plus: ^1.0.0
  flutter_blurhash: ^0.6.0
  country_code_picker: ^2.0.1
  universal_platform: ^1.0.0+1
  uuid: ^3.0.1
  collection: ^1.15.0
  decimal: ^1.3.0
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  timezone: ^0.7.0
  flutter_countdown_timer: ^4.1.0
  time: ^2.0.0
  sized_context: ^1.0.0-nullsafety
  google_sign_in: ^5.0.5
  flutter_linkify: ^5.0.2
  timezone_name:
    git:
      url: https://github.com/peerwaya/timezone_name.git
  percent_indicator: ^3.0.1
  flutter_local_notifications: ^6.0.0
  crypto: ^3.0.0
  tuple: ^2.0.0
  wiredash: ^0.7.0+1
  styled_widget: ^0.3.1
  js: ^0.6.3
  flutter_dropzone: ^2.0.1
  browser_adapter:
    git:
      url: https://github.com/KurobiHq/browser_adapter.git
  interval_tree:
    git:
      url: https://github.com/GotokHQ/interval_tree.git
  flutter_secure_storage: ^4.2.0
  permission_handler: ^8.1.4+2
  provider: ^5.0.0
  flutter_svg: ^0.23.0+1
  safe_insets:
    git:
      url: https://github.com/peerwaya/safe_insets.git
  qr_utils:
    git:
      url: https://github.com/peerwaya/qr_utils.git 
  webview_flutter: ^2.0.6
  email_validator: '^2.0.1'
  pointer_interceptor: ^0.9.0+1
  sentry_flutter: ^5.0.0
  fluttertoast: ^8.0.7
  torus_firebase_jwt:
    git:
      url: https://github.com/KurobiHq/torus-firebase-jwt
  solana:
    git:
      url: https://github.com/KurobiHq/cryptoplease-dart.git
      path: packages/solana
  http: ^0.13.0
  #call plugins
  web_socket_channel:
    git:
      url: https://github.com/GotokHQ/web_socket_channel.git
  after_layout: ^1.1.0
  flutter_keyboard_visibility: ^5.0.2
  bubble: ^1.2.1
  dotenv: ^3.0.0
  backdrop: ^0.6.2
  carousel_slider: ^4.0.0

dependency_overrides:
  pointycastle: ^3.2.0-rc0
  url_launcher_web: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

analyzer:
  enable-experiment:
    - spread-collections
    - control-flow-collections
    - non-nullable

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - packages/timezone/data/latest.tzf
    - assets/svg/calendar-month-outline.svg
    - assets/svg/calendar-alert.svg
    - assets/svg/circle-small.svg
    - assets/images/social_icons/
    - assets/images/user/small/
    - assets/images/user/large/
    - assets/images/klogo/
    - assets/images/glogo/
    - assets/images/nft/
    - assets/images/patterns/
    - assets/images/contribution/
    - assets/images/pattern/
    - assets/images/logo_full/dark/small/
    - assets/images/logo_full/light/small/
    - assets/images/stripe/
    - assets/images/torus/
    - assets/images/payment_methods/
    - assets/images/payment_methods/dark/
    - assets/images/payment_methods/light/
    - assets/images/coinbase_commerce/logo.svg
    - assets/images/coinbase_commerce/
    - assets/images/google/
    - assets/images/google/google.svg
    - assets/images/twitter/
    - assets/images/twitter/twitter.svg
    - assets/images/service/no-region-dark.svg
    - assets/images/service/no-region-light.svg
    - assets/images/apple/
    - assets/images/facebook/
    - assets/images/facebook/facebook.svg
    - assets/models/nsfw/labels.txt
    - assets/images/usdc/usdc.svg
    - assets/images/solana/solana.svg
    - assets/images/usdt/usdt.svg
    - assets/images/kin/kin.svg
    - assets/data/markets.json
    - assets/images/transack/transack.png
    - assets/images/ramp/
    - assets/images/ftx/ftx.svg
    - assets/images/wallets/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
