name: CI
on:
  push:
    branches:
      - develop
jobs:
  build_solana_web_client:
    name: Build Solana Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          cd packages/solana-web-client
          npm install
          npm run build
      - name: Archive Solana Web Artifact
        uses: actions/upload-artifact@master
        with:
          name: solana-web-client-build
          path: packages/solana-web-client/lib
  build_web_app:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    needs: build_solana_web_client
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@master
      with:
          channel: 'master'
    - run: git config --global url."https://${{ secrets.GIT_USER }}:${{ secrets.GIT_TOKEN }}@github.com/".insteadOf https://github.com/
    - name: Configure flutter
      run: |
          cd packages/app
          flutter pub get
          flutter config --enable-web
    - name: Run dart env
      run: cd packages/app && dart tool/env.dart
      env:
          WIREDASH_DASH_SECRET: ${{ secrets.DEV_WIREDASH_DASH_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          VAPID_KEY: ${{ secrets.DEV_VAPID_KEY }}
          DSN: ${{ secrets.WEB_DSN }}
          PASSBASE_API_KEY: ${{ secrets.DEV_PASSBASE_API_KEY }} 
          TRANSACK_API_KEY: ${{ secrets.DEV_TRANSACK_API_KEY }}
          FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          SENTRY_RELEASE_NAME: ${{ github.run_id }}-${{ github.run_number }}-dev 
          CONFIG_FILE_NAME: tool/dev.env
          RECAPTCHA_V3: ${{ secrets.KUROBI_BETA_RECAPTCHA_V3 }}
          RAMP_API_KEY: ${{ secrets.DEV_RAMP_API_KEY }}
    - name: Run Web env
      run: |
            . packages/app/parse-tmp-env.sh ./packages/app/web/index.example.html ./packages/app/web/index.html
            . packages/app/parse-tmp-env.sh ./packages/app/web/manifest.example.json ./packages/app/web/manifest.json
            . packages/app/parse-tmp-env.sh ./packages/app/web/firebase-messaging-sw.example.js ./packages/app/web/firebase-messaging-sw.js
      env:
          APP_NAME: Kurobi
          APP_TITLE: Monetize your time
          APP_DESCRIPTION: Accept 1:1 call bookings, sell NFT Tickets for live events and get paid in crypto or cash
          APP_BACKGROUND_COLOR: "#141927"
          APP_THEME_LIGHT_COLOR: "#ffffff"
          APP_THEME_DARK_COLOR: "#2a2a2a"
          APP_ICON_SVG: icons/kurobi.svg
          APP_ICON_MASKABLE_PNG_512: icons/kurobi-maskable-512.png    
          APP_ICON_MASKABLE_PNG_192: icons/kurobi-maskable-192.png
          APP_ICON_PNG_512: icons/kurobi-512.png
          APP_ICON_PNG_192: icons/kurobi-192.png
          APP_SHORT_NAME: Kurobi - Monetize your time
          FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
          FIREBASE_PROJECT_ID: kurobidev-182a5
          FIREBASE_STORAGE_BUCKET: kurobidev-182a5.appspot.com
          FIREBASE_MESSAGING_SENDER_ID: 878753935040
          FIREBASE_APP_ID: 1:878753935040:web:2d55a73b0a7f9126ebc725
          FIREBASE_MEASUREMENT_ID: G-VPRYHFYYMD
          FIREBASE_ANDROID_CLIENT_ID: 878753935040-atste69i9q6q5f923f9rsktqt2ppbh92.apps.googleusercontent.com
          FIREBASE_IOS_CLIENT_ID: 878753935040-frv72693bo58e9oak9je8p8ebue1puif.apps.googleusercontent.com
          FIREBASE_DATABASE_URL: https://kurobidev-182a5.firebaseio.com
          FIREBASE_AUTH_DOMAIN: kurobidev-182a5.firebaseapp.com
          RECAPTCHA_V3: ${{ secrets.KUROBI_DEV_RECAPTCHA_V3 }}
          FACEBOOK_APP_ID: 384554333075061 
          APP_VERSION: ${{ github.run_id }}-${{ github.run_number }}-dev 
    - run: cd packages/app && flutter build web -t lib/main_dev.dart --web-renderer canvaskit --source-maps #--web-renderer canvaskit
      #- run: sed -i 's/q.autoplay=!0/q.autoplay=1/g' build/web/main.dart.js
    - name: Download Solana Web Client
      uses: actions/download-artifact@master
      with:
        name: solana-web-client-build
        path: packages/app/build/web/solana-web-client
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: web-build
        path: packages/app/build/web

  deploy_web_app_aws:
    name: Deploy Web to AWS s3
    needs: build_web_app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
          path: build/web

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Deploy static site to S3 bucket
        env:
            S3_BUCKET_NAME: dev-kurobi
            S3_CACHE_MAX_AGE: 31536000
        run: |
          aws s3 sync build/web s3://$S3_BUCKET_NAME --delete
          aws s3 cp s3://$S3_BUCKET_NAME/ s3://$S3_BUCKET_NAME/ --metadata-directive REPLACE \
          --exclude "*" --include "*.jpg" --include "*.gif" --include "*.png" \
          --recursive --cache-control max-age=$S3_CACHE_MAX_AGE
      - name: Invalidate Cloud front distribution
        env:
            CLOUD_FRONT_DISTRIBUTION: E1HJVYSSQXJJSD
        run: aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_DISTRIBUTION --paths "/*"
      - name: Install Sentry cli      
        run: curl -sL https://sentry.io/get-cli/ | bash
      - name: Upload release to sentry
        run: |
            sentry-cli releases new ${{ github.run_id }}-${{ github.run_number }}-dev  
            sentry-cli releases files ${{ github.run_id }}-${{ github.run_number }}-dev  upload-sourcemaps build/web
            sentry-cli releases finalize ${{ github.run_id }}-${{ github.run_number }}-dev 
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.WEB_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }} 
        